gateway: "10.8.0.1"
domains:
- "protonmail.com"
- "account.protonmail.com"
- "mail.protonmail.com"
- "vpsie.com"
- "linkedin.com"
- "ru.linkedin.com"
- "rutracker.org"
- "gulagu.net"
- "torproject.org"
- "ovdinfo.org"
- "navalny.com"
- "readovka.news"
- "tvrain.ru"
- "echo.msk.ru"
- "twitter.com"
- "facebook.com"
- "instagram.com"
- "i.instagram.com"
- "graph.instagram.com"
- "meduza.io"
