gateway: "10.8.0.1"
domains:
- "bbc.com"
- "ru.bellingcat.com"
- "ru.euronews.com"
- "facebook.com"
- "static.xx.fbcdn.net"
- "news.google.com"
- "gulagu.net"
- "instagram.com"
- "i.instagram.com"
- "graph.instagram.com"
- "linkedin.com"
- "ru.linkedin.com"
- "meduza.io"
- "echo.msk.ru"
- "navalny.com"
- "nevzorov.tv"
- "ovdinfo.org"
- "readovka.news"
- "rutracker.org"
- "tjournal.ru"
- "torproject.org"
- "tvrain.ru"
- "twitter.com"
- "mobile.twitter.com"
- "protonmail.com"
- "account.protonmail.com"
- "mail.protonmail.com"
- "vpsie.com"
- "zona.media"