domains:
- bbc.com
- ru.bellingcat.com
- chess.com
- www.chess.com
- doxajournal.ru
- ru.euronews.com
- facebook.com
- static.xx.fbcdn.net
- news.google.com
- gulagu.net
- holod.media
- instagram.com
- graph.instagram.com
- i.instagram.com
- www.instagram.com
- linkedin.com
- ru.linkedin.com
- meduza.io
- echo.msk.ru
- mult.ru
- multru.com
- navalny.com
- nevzorov.tv
- ovdinfo.org
- paperpaper.ru
- proton.me
- account.proton.me
- protonmail.com
- account.protonmail.com
- mail.protonmail.com
- readovka.news
- rutracker.org
- tjournal.ru
- torproject.org
- tvrain.ru
- twitter.com
- mobile.twitter.com
- vpsie.com
- zona.media
gateway: 10.8.0.1
